export const provincias = [
    { comunidad: '01', codigo: '04', nombre: 'Almería' },
    { comunidad: '01', codigo: '11', nombre: 'Cádiz' },
    { comunidad: '01', codigo: '14', nombre: 'Córdoba' },
    { comunidad: '01', codigo: '18', nombre: 'Granada' },
    { comunidad: '01', codigo: '21', nombre: 'Huelva' },
    { comunidad: '01', codigo: '23', nombre: 'Jaen' },
    { comunidad: '01', codigo: '29', nombre: 'Málaga' },
    { comunidad: '01', codigo: '41', nombre: 'Sevilla' },
    { comunidad: '02', codigo: '22', nombre: 'Huesca' },
    { comunidad: '02', codigo: '44', nombre: 'Teruel' },
    { comunidad: '02', codigo: '50', nombre: 'Zaragoza' },
    { comunidad: '03', codigo: '33', nombre: 'Asturias' },
    { comunidad: '04', codigo: '07', nombre: 'Balears, Illes' },
    { comunidad: '05', codigo: '35', nombre: 'Palmas, Las' },
    { comunidad: '05', codigo: '38', nombre: 'Santa Cruz de Tenerife' },
    { comunidad: '06', codigo: '39', nombre: 'Cantabria' },
    { comunidad: '07', codigo: '05', nombre: 'Ávila' },
    { comunidad: '07', codigo: '09', nombre: 'Burgos' },
    { comunidad: '07', codigo: '24', nombre: 'León' },
    { comunidad: '07', codigo: '34', nombre: 'Palencia' },
    { comunidad: '07', codigo: '37', nombre: 'Salamanca' },
    { comunidad: '07', codigo: '40', nombre: 'Segovia' },
    { comunidad: '07', codigo: '42', nombre: 'Soria' },
    { comunidad: '07', codigo: '47', nombre: 'Valladolid' },
    { comunidad: '07', codigo: '49', nombre: 'Zamora' },
    { comunidad: '08', codigo: '02', nombre: 'Albacete' },
    { comunidad: '08', codigo: '13', nombre: 'Ciudad Real' },
    { comunidad: '08', codigo: '16', nombre: 'Cuenca' },
    { comunidad: '08', codigo: '19', nombre: 'Guadalajara' },
    { comunidad: '08', codigo: '45', nombre: 'Toledo' },
    { comunidad: '09', codigo: '08', nombre: 'Barcelona' },
    { comunidad: '09', codigo: '17', nombre: 'Girona' },
    { comunidad: '09', codigo: '25', nombre: 'Lleida' },
    { comunidad: '09', codigo: '43', nombre: 'Tarragona' },
    { comunidad: '10', codigo: '03', nombre: 'Alicante/Alacant' },
    { comunidad: '10', codigo: '12', nombre: 'Castellón/Castelló' },
    { comunidad: '10', codigo: '46', nombre: 'Valencia/València' },
    { comunidad: '11', codigo: '06', nombre: 'Badajoz' },
    { comunidad: '11', codigo: '10', nombre: 'Cáceres' },
    { comunidad: '12', codigo: '15', nombre: 'Coruña, A' },
    { comunidad: '12', codigo: '27', nombre: 'Lugo' },
    { comunidad: '12', codigo: '32', nombre: 'Ourense' },
    { comunidad: '12', codigo: '36', nombre: 'Pontevedra' },
    { comunidad: '13', codigo: '28', nombre: 'Madrid' },
    { comunidad: '14', codigo: '30', nombre: 'Murcia' },
    { comunidad: '15', codigo: '31', nombre: 'Navarra' },
    { comunidad: '16', codigo: '01', nombre: 'Araba/Álava' },
    { comunidad: '16', codigo: '48', nombre: 'Bizkaia' },
    { comunidad: '16', codigo: '20', nombre: 'Gipuzkoa' },
    { comunidad: '17', codigo: '26', nombre: 'Rioja, La' },
    { comunidad: '18', codigo: '51', nombre: 'Ceuta' },
    { comunidad: '19', codigo: '52', nombre: 'Melilla' },
];